"""API 模块 — 显式挂载子模块。

main.py 使用 `from src.api import add_friend_api` 等形式聚合导入。
若 __init__.py 为空，PyInstaller 冻结包可能无法把子模块打进依赖图，运行时报
`cannot import name 'add_friend_api' from 'src.api'`。
"""

from . import (
    add_friend_api,
    agent_api,
    ai_media_api,
    auto_follow_api,
    chat,
    config_api,
    crm_api,
    crm_customer_api,
    file_api,
    friend_api,
    friend_sync_api,
    friend_backup_api,
    friend_filter_api,
    instance_api,
    knowledge_file_api,
    license_api,
    manual_compose_api,
    direct_bg_api,
    canvas_compose_api,
    moment_api,
    moment_schedule_api,
    moment_plan_group_api,
    moment_comment_api,
    scheduler_api,
    script_api,
    stats_api,
    system,
    tag_api,
    task_api,
    ui_bus_api,
    openapi_api,
    keyword_reply_api,
    chat_knowledge_api,
    sales_market_api,
    fulfillment_api,
)

__all__ = [
    "add_friend_api",
    "agent_api",
    "ai_media_api",
    "auto_follow_api",
    "chat",
    "config_api",
    "crm_api",
    "crm_customer_api",
    "file_api",
    "friend_api",
    "friend_sync_api",
    "friend_backup_api",
    "friend_filter_api",
    "instance_api",
    "knowledge_file_api",
    "license_api",
    "manual_compose_api",
    "direct_bg_api",
    "canvas_compose_api",
    "moment_api",
    "moment_schedule_api",
    "moment_plan_group_api",
    "moment_comment_api",
    "scheduler_api",
    "script_api",
    "stats_api",
    "system",
    "tag_api",
    "task_api",
    "ui_bus_api",
    "openapi_api",
    "keyword_reply_api",
    "chat_knowledge_api",
    "sales_market_api",
    "fulfillment_api",
]

